### ISSUE TITLE
Unmanaged mode returns nothing after IAP complete

### ISSUE THREAD

**Issue by gonzdevour** [ludei/Construct-2-plugin#29]
Unmanaged mode returns nothing after IAP complete, no matter succeeded or failed.

Since managed mode made apps with IAP can't pass Apple's review,
I think we need another way to submit our apps.
And it looks like unmanaged mode has something wrong to get IAP result.

I tested unmanaged mode today on iOS and I can't finish purchase progress in sandbox.
The Sandbox showed success message but CocoonJS plugin can't get complete signal in return.
(Same code worked fine in managed mode)

**Comment by LibelulaV** [comment]
Hello, 

We are currently working on adapting the atomic plugins for C2. The next one will be one for InApps. 
However, about the unmanaged mode, it makes sense. In order to use the unmanaged mode in C2 you must edit the plugin and include your own verification function. You need to verified the purchases on your own. 

We will try to figure out a solution for the new plugin, because I am not sure if we will face the same problem. 

Do you know any plugin for InApps that allows users to set the unmanaged mode on their own, including the verifying function? It would be quite useful. Depending on how it is done, I might be able to add a fix here too, if it doesn't require a lot of refactoring. 

Regards.

**Comment by gonzdevour** [comment]
Sorry I am not a real programmer. As far as I know the difference between managed mode and unmanaged mode is that Ludei's server will help us to verify if a purchase is a legal access or not in managed mode. I tried to use unmanaged mode just because the managed mode made my app can't pass the appstore review. When the managed mode worked after the plugin being fixed, there's no reason for us to try unmanaged mode again. 

As far as I know, other iap plugins of C2 don't have server to manage the verification. It simply calls the official IAP functions.

C2 Officail IAP Plugin:
https://www.scirra.com/manual/173/iap

C2 3rd-Party IAP Plugin for Cordova/Crosswalk(IntelXDK)
https://www.scirra.com/forum/plugins-cordova-related-c2-plugins-crosswalk-list_p800966?#p800966

I am not sure if the information above helps or not, if not, you may know the main thread of Ludei's plugin update in C2 official site:
https://www.scirra.com/forum/cocoonjs-plugin-updates_p895105?#p895105

**Comment by LibelulaV** [comment]
I will have a look at them anyway in case I can improve the feature. 
Thanks a lot for the links. 

I will close this issue. 

Regards.
